version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: url_shortener_mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 11111111
    volumes:
      - mongo-data:/data/db
    networks:
      - app_net

  app:
    build: .
    container_name: url_shortener_app
    restart: always
    ports:
      - "8081:8081"
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - mongo
    networks:
      - app_net

volumes:
  mongo-data:

networks:
  app_net:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"